site_name: ARPES manual (SUV, SSLS)
repo_url: https://pranabdas.github.io 
site_description: ARPES manual for SUV beamline at SSLS, NUS.
site_author: Pranab Das 

nav:
    - Home: index.md 
    - Operation of helium lamp: helium-lamp-operation.md 
    - Procedure to purge helium gas line: purge-helium-line.md 
    - Analyzer slit dimension: slit-dim.md 
    - SCIENTA Power Supply Connections: power-supply-connections.md 
    - Supply information for Spin measurements: spin-supply.md 
    - Data analysis: data-analysis.md 
    - Resolution: resolution.md 

theme: 
    name: null 
    custom_dir: simplicity  
    static_templates:
        - 404.html

    include_search_page: true
    search_index_only: false

    highlightjs: true
    hljs_languages: python 

markdown_extensions:
  - pymdownx.arithmatex 

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

copyright: © Copyright 2020 Pranab Das. All rights reserved. 

# google_analytics: [UA-163317742-1, https://pranabdas.github.io/]
