site_name: ARPES Manual
repo_url: https://pranabdas.github.io/
site_description: ARPES manual for SUV beamline at SSLS, NUS.
site_author: Pranab Das

nav:
    - Table of Contents: index.md
    - About System: system-details.md
    - Sample mounting: sample-mounting.md
    - Operation of helium lamp: helium-lamp-operation.md
    - Procedure to purge helium gas line: purge-helium-line.md
    - Analyzer slit dimension: slit-dim.md
    - SCIENTA Power Supply Connections: power-supply-connections.md
    - Supply information for Spin measurements: spin-supply.md
    - Manipulator operation: manipulator.md
    - X-ray source operation: x-ray.md
    - Sputter gun operation: sputtering.md
    - Heating stage operation: heating.md
    - Analyzer Operation: analyzer.md
    - Data analysis: data-analysis.md
    - ARPES Resolution: resolution.md
    - Backing chambers: baking.md
    - Miscellaneous: misc.md

theme:
    name: null
    custom_dir: simplicity
    static_templates:
        - 404.html

    include_search_page: true
    search_index_only: false

    highlightjs: true

markdown_extensions:
    - pymdownx.arithmatex
    - attr_list

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
